export const FETCH_TASKS_LOADING = "FETCH_TASKS_LOADING";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_ERROR = "FETCH_TASKS_ERROR";
export const TASKS_SET_PAGE = "TASKS_SET_PAGE";

export const ADD_TASK_RESET = "ADD_TASK_RESET";
export const ADD_TASK_LOADING = "ADD_TASK_LOADING";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_LOADING";
export const ADD_TASK_SET_USERNAME = "ADD_TASK_SET_USERNAME";
export const ADD_TASK_SET_EMAIL = "ADD_TASK_SET_EMAIL";
export const ADD_TASK_SET_TEXT = "ADD_TASK_SET_TEXT";
export const ADD_TASK_SET_STATUS = "ADD_TASK_SET_STATUS";
export const ADD_TASK_OPEN_DIALOG = "ADD_TASK_OPEN_DIALOG";

export const SIGN_IN_SET_USERNAME = "SIGN_IN_SET_USERNAME";
export const SIGN_IN_SET_PASSWORD = "SIGN_IN_SET_PASSWORD";
export const SIGN_IN_LOADING = "SIGN_IN_LOADING";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_IN_OPEN_DIALOG = "SIGN_IN_OPEN_DIALOG";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_IN_RESET_ERRORS = "SIGN_IN_RESET_ERRORS";

export const EDIT_TASK_LOADING = "EDIT_TASK_LOADING";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";
export const EDIT_TASK_SET_TEXT = "EDIT_TASK_SET_TEXT";
export const EDIT_TASK_SET_STATUS = "EDIT_TASK_SET_STATUS";
export const EDIT_TASK_OPEN_DIALOG = "EDIT_TASK_OPEN_DIALOG";
